version: 2 

sources: 
  - name: src_github
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    loader: airflow
    
    tables: 
      - name: create_events
        description: Table contains only CreateEvent types from the event stream
        columns: 
          - name: id
            tests: 
              - unique

  - name: github_repos
    database: bigquery-public-data
    tables:
      - name: languages

models:
  - name: github_repo_languages
    description: Extracting languages used in a repository

  - name: github_events
    description: Extracting only PushEvent and CreateEvent from the source Github Archive events
    columns: 
      - name: id
        tests:
          - unique