config:
  partial_parse: true
  use_colors: true
github_events_transform:
  outputs:
    dev:
      dataset: dbt
      fixed_retries: 1
      keyfile: /path/to/keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 32
      timeout_seconds: 300
      type: bigquery
  target: dev
